=== abstha/GIft-Card-website/catalog_20048807.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- defining simple type elements-->
    <xs:element name="st_logo" type="xs:anyURI"/>
    <xs:element name="st_name" type="xs:string"/>
    <xs:element name="home" type="xs:string"/>
    <xs:element name="products" type="xs:string"/>
    <xs:element name="search" type="xs:string"/>
    <xs:element name="cost" type="xs:positiveInteger"/>
    <xs:element name="validity" type="xs:string"/>
    <xs:element name="users" type="xs:positiveInteger"/>
    <xs:element name="vouchers" type="xs:positiveInteger"/>
    <xs:element name="platform" type="xs:string"/>
    <xs:element name="availability" type="xs:string"/>
    <xs:element name="dm1" type="xs:string"/>
    <xs:element name="dm2" type="xs:string"/>
    <xs:element name="e-mail" type="xs:string"/>
    <xs:element name="return" type="xs:string"/>
    <xs:element name="refund" type="xs:string"/>
    <xs:element name="paymentmeth" type="xs:string"/> 
    <xs:element name="contactus" type="xs:string"/>
    <xs:element name="Customerservice" type="xs:string"/>
    <xs:element name="webaddress" type="xs:string"/>
    <xs:element name="situated" type="xs:string"/>
    <xs:element name="state" type="xs:string"/>
    <xs:element name="street" type="xs:string"/>
    <xs:element name="telenum" type="xs:integer"/>

    <!-- defining attributes-->
    <xs:attribute name="des" type="xs:string"/>
    <xs:attribute name="category"  type="xs:string" />
    <xs:attribute name="p_id" type="xs:ID"/>
    <xs:attribute name="atr" type="xs:string"/>
    <xs:attribute name="un_id" type="xs:ID" />
    <xs:attribute name="type" type="xs:ID"/>
    <xs:attribute name="currency" type="xs:string"/>
    <xs:attribute name="zip_code" type="xs:string"/>

    <!-- defining complex elements-->
    <xs:element name="header">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="st_logo" maxOccurs="1"/>
                <xs:element ref="st_name"/>
                <xs:element name="nav_bar"/>
            </xs:sequence>
            <xs:attribute ref="des"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="nav_bar">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="home"/>
                <xs:element ref="products"/>
                <xs:element ref="search"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="body">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="giftcards"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="giftcards">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="row">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="giftcard" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="image">
        <xs:complexType>
            <xs:attribute ref="atr" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="type">
        <xs:complexType mixed="true">
            <xs:attribute ref="un_id" use="optional"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="giftcard" >
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="image"/>
                <xs:element ref="type"/>
                <xs:element ref="cost"/>
                <xs:element ref="validity"/>
                <xs:element ref="users"/>
                <xs:element ref="vouchers" minOccurs="0"/>
                <xs:element ref="platform"/>
                <xs:element ref="availability"/>
                <xs:element name="delivery_mode" minOccurs="0"/>
                <xs:element name="recepient" minOccurs="0"/>
                <xs:element name="cashback" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="category" use="required" />
            <xs:attribute ref="p_id" use="required"/>
            <xs:attribute ref="atr" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="delivery_mode">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dm1" minOccurs="0"/>
                <xs:element ref="dm2" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="recepient">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="e-mail" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="cashback">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="return" minOccurs="0"/>
                <xs:element ref="refund" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="currency" use="optional"/>
            <xs:attribute ref="type" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="footer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="help"/>
                <xs:element name="storedetails"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>



    <xs:element name="help">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="paymentmeth"/>
                <xs:element ref="contactus"/>
                <xs:element ref="Customerservice"/>
                <xs:element ref="webaddress"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="storedetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="locations"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="locations">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="situated"/>
                <xs:element name="country"/>
                <xs:element ref="state"/>
                <xs:element ref="street"/>
                <xs:element ref="telenum"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="country">
        <xs:complexType>
            <xs:attribute ref="zip_code" use="optional"/>
        </xs:complexType>
    </xs:element>
    

    <!-- defining complete xml document-->

    <xs:element name="agiftcard">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="header"/>
                <xs:element ref="body"/>
                <xs:element ref="footer"/>
            </xs:sequence>
        </xs:complexType>   
    </xs:element>
</xs:schema>

=== abstha/GIft-Card-website/catalog_20048807.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/css" href="catalog_20048807.css"?>
<agiftcard xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20048807.xsd">
    <header des="header">
        <st_logo></st_logo>
        <st_name>Relik gaming</st_name>
        <nav_bar>
            <home>HOME</home>
            <products>PRODUCTS</products>
            <search>SEARCH</search>
        </nav_bar>
    </header>
    
    <body>
        <giftcards >
            <row>
                <giftcard category="gaming" p_id="gc01" >
                    <image atr="img1"/>
                    <type>type: physical</type><!-- physical ID have no unique ID-->
                    <cost> 10</cost>
                    <validity>validity: 2 years</validity>
                    <users> 2</users>
                    <vouchers> 15</vouchers>
                    <platform>platform: steam</platform>
                    <availability>availability: available</availability>
                    <delivery_mode>
                        <dm1>deliverymode1: Instant</dm1>
                        <dm2>deliverymode2: 1 week</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail></e-mail>
                    </recepient>
                    <cashback>
                        <return>return: no</return>
                        <refund>refund: only in case of damage.</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
                <giftcard category="entertainment" p_id="gc02">
                    <image atr="img2"></image>
                    <type un_id="dgc1">type: digital</type><!-- unique element for digital gift cards in schema -->
                    <cost>15</cost>
                    <validity>validity: 1 time</validity>
                    <users> 1</users>
                    <vouchers> 10</vouchers>
                    <platform>platform: crunchyroll</platform>
                    <availability>availability: available</availability>
                    <delivery_mode>
                        <dm1>dm1: Instant</dm1>
                        <dm2>dm2: 24 hrs</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail></e-mail>
                    </recepient>
                    <cashback>
                        <return>return: yes</return>
                        <refund>refund: only in case of damage.</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
                <giftcard category="restaurant" p_id="gc03">
                    <image atr="img3"></image>
                    <type un_id="dgc2">type: digital</type><!-- unique element for schema -->
                    <cost>5</cost>
                    <validity>validity: 3 years</validity>
                    <users> 3</users>
                    <vouchers> 10</vouchers>
                    <platform>platform: Nando's</platform>s
                    <availability>availability: not-available</availability>
                    <delivery_mode>
                        <dm1>dm1: 1 week</dm1>
                        <dm2>dm2: 2 weeks</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail></e-mail>
                    </recepient>
                    <cashback>
                        <return>return: no</return>
                        <refund>refund: only in case of damage.</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
                
                
                <giftcard category="ride-sharing" p_id="gc04">
                    <image atr="img4"></image>
                    <type>type: physical</type>
                    <cost>20</cost>
                    <validity>validity: 6 months</validity>
                    <users>4</users>
                    <vouchers> 20</vouchers>
                    <platform>platform: uber</platform>
                    <availability>availability: available</availability>
                    <delivery_mode>
                        <dm1>dm1: Instant</dm1>
                        <dm2>dm2: 1 week</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail></e-mail>
                    </recepient>
                    <cashback>
                        <return>return: no</return>
                        <refund>refund: only in case of damage.</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
                <giftcard category="e-commerce" p_id="gc05">
                    <image atr="img5"></image>
                    <type>type: physical</type>
                    <cost>25</cost>
                    <validity>validity: 1 years</validity>
                    <users> 2</users>
                    <vouchers> 15</vouchers>
                    <platform>platform: E-Bay</platform>
                    <availability>availability: available</availability>
                    <delivery_mode>
                        <dm1>dm1: Instant</dm1>
                        <dm2>dm2: 1 week</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail>E-mail</e-mail>
                    </recepient>
                    <cashback>
                        <return>return: no</return>
                        <refund>refund: only in case of damage.</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
                <giftcard category="gaming" p_id="gc06">
                    <image atr="img6"></image>
                    <type un_id="dgc3">type: digital</type>
                    <cost>20</cost>
                    <validity>validity: 1 year</validity>
                    <users> 1</users>
                    <vouchers> 30</vouchers>
                    <platform>platform: PUBG</platform>
                    <availability>availability: not available</availability>
                    <delivery_mode>
                        <dm1>dm1: Instant</dm1>
                        <dm2>dm2: 3 days</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail></e-mail>
                    </recepient>
                    <cashback>
                        <return>return: yes</return>
                        <refund>refund: only in case of damage</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
                <giftcard category="e-commerce" p_id="gc07">
                    <image atr="img7"></image>
                    <type>type: physical</type>
                    <cost>10</cost>
                    <validity>validity: 2 year</validity>
                    <users> 4</users>
                    <vouchers> 40</vouchers>
                    <platform>platform: google play</platform>
                    <availability>availability: available</availability>
                    <delivery_mode>
                        <dm1>dm1: Instant</dm1>
                        <dm2>dm2: 2 days</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail></e-mail>
                    </recepient>
                    <cashback>
                        <return>return: no</return>
                        <refund>refund: only in case of damage</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
                <giftcard category="gaming" p_id="gc08">
                    <image atr="img8"></image>
                    <type>type: physical</type>
                    <cost>15</cost>
                    <validity>validity: 3 year</validity>
                    <users> 3</users>
                    <vouchers> 20</vouchers>
                    <platform>platform: fortnite</platform>
                    <availability>availability: not available</availability>
                    <delivery_mode>
                        <dm1>dm1: Instant</dm1>
                        <dm2>dm2: 6 days</dm2>
                    </delivery_mode>
                    <recepient>
                        <e-mail></e-mail>
                    </recepient>
                    <cashback currency="dollar" type="online">
                        <return>return: no</return>
                        <refund>refund: only in case of damage</refund>
                    </cashback>
                    <add>Add to cart</add>
                </giftcard>
            </row>
        </giftcards>
    </body>
    <footer>
        <help>
            <paymentmeth>Payment method</paymentmeth>
            <contactus>Contact Us</contactus>
            <Customerservice>Customer Service</Customerservice>
            <webaddress>www.relikstore.com</webaddress>
        </help>
        <storedetails>
            <locations>
                <situated>Location:</situated>
                <country zip_code="CB21">UK</country>
                <state>State: london</state>
                <street>Street: Downing street</street>
                <telenum>+4420898839</telenum>
            </locations>       
        </storedetails>
    </footer>
</agiftcard>
